import * as z from 'zod';

export const productSchema = z.object({
  id: z.string().default(''),
  name: z.string().default(''),
  description: z.string().default(''),
  detailed_description: z.string().default(''),
  original_price: z.string().default(''),
  price: z.string().default(''),
  category: z.enum(['cosmetics', 'hair-extension']).default('cosmetics'),
  status: z.enum(['draft', 'published', 'archived']).default('draft'),
  featured: z.boolean().default(false),
  in_stock: z.boolean().default(false),
  stock_quantity: z.string().default(''),
  sku: z.string().default(''),
  weight: z.string().default(''),
  dimensions: z.string().default(''),
  ingredients: z.string().default(''),
  skin_type: z.string().default(''),
  product_benefits: z.string().default(''),
  spf_level: z.string().default(''),
  volume_size: z.string().default(''),
  dermatologist_tested: z.boolean().default(false),
  cruelty_free: z.boolean().default(false),
  organic_natural: z.boolean().default(false),
  hair_type: z.string().default(''),
  hair_texture: z.string().default(''),
  hair_length: z.string().default(''),
  hair_weight: z.string().default(''),
  hair_color: z.string().default(''),
  hair_color_shade: z.string().default(''),
  installation_method: z.string().default(''),
  care_instructions: z.string().default(''),
  quantity_in_set: z.string().default(''),
  seo_title: z.string().default(''),
  seo_description: z.string().default(''),
  seo_keywords: z.string().default(''),
  main_image_url: z.string().default(''),
  gallery_urls: z.array(z.string()).default([]),
});

export type ProductFormData = z.infer<typeof productSchema>; 